-- Create database
CREATE DATABASE IF NOT EXISTS `shelflife`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_general_ci;

USE `shelflife`;

-- Optional settings for character set, timezone, etc.
SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT;
SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS;
SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION;
SET NAMES utf8mb4;
SET @OLD_TIME_ZONE=@@TIME_ZONE;
SET TIME_ZONE='+00:00';
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS;
SET UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE;
SET SQL_MODE='NO_AUTO_VALUE_ON_ZERO';
SET @OLD_SQL_NOTES=@@SQL_NOTES;
SET SQL_NOTES=0;

-- Drop and recreate Reads table
DROP TABLE IF EXISTS `Reads`;

CREATE TABLE `Reads` (
  `isbn` VARCHAR(20) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `hasRead` TINYINT(1) DEFAULT 0,
  `willRead` TINYINT(1) DEFAULT 0,
  `hasNotCompleted` TINYINT(1) DEFAULT 0,
  `owns` TINYINT(1) DEFAULT 0,
  `startDate` DATE DEFAULT NULL,
  `endDate` DATE DEFAULT NULL,
  PRIMARY KEY (`isbn`, `username`),
  KEY `username` (`username`),
  CONSTRAINT `Reads_ibfk_1` FOREIGN KEY (`isbn`) REFERENCES `Edition` (`isbn`) ON DELETE CASCADE,
  CONSTRAINT `Reads_ibfk_2` FOREIGN KEY (`username`) REFERENCES `User` (`username`) ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_general_ci;

-- Restore previous session settings
SET TIME_ZONE=@OLD_TIME_ZONE;
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT;
SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS;
SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION;
SET SQL_NOTES=@OLD_SQL_NOTES;

